disabled_rules:
  - line_length
  - trailing_whitespace

type_name:
  min_length: 2
  max_length: 50

identifier_name:
  min_length: 2

function_body_length:
  warning: 60
  error: 100

cyclomatic_complexity:
  warning: 15
  error: 20

excluded:
  - ios/fastlane
