# Always check for a fastlane update
update_fastlane

# This is the minimum version number required.
fastlane_version "1.22.0"

default_platform :ios

platform :ios do

  before_all do
    increment_build_number
    gym

    # xctool # run the tests of your app
  end

  desc "Build and create Screenshots"
  lane :screenshots do
    snapshot
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    sigh
    deliver(beta: true)
  end

  desc "Deploy a new version to the App Store"
  desc "** Full Markdown** Support: `code`"
  lane :deploy do
    sigh
    deliver(skip_deploy: true, force: true)
  end

  # After Actions

  after_all do |lane|
    # Only called if successful
  end

  error do |lane, exception|
  end
end
