devices([
  "iPhone 6",
  "iPhone 6 Plus",
  "iPhone 5",
  "iPhone 4s",
  "iPad Retina",
  "iPad Pro"
])

languages([
  "en-US"
])

project "./Bike Buddy.xcodeproj"
scheme "Bike Buddy"

clear_previous_screenshots true
