default_platform(:ios)

platform :ios do
  desc "Capture light and dark screenshots for AppStore/compose.py"
  lane :screenshots do
    snapshot(output_directory: "./fastlane/screenshots/light", dark_mode: false)
    snapshot(output_directory: "./fastlane/screenshots/dark",  dark_mode: true)
  end
end
